version: '3.1'
services:
  mysql:
    image: mysql:8
    ports:
      - "3306:3306"

    environment:
        MYSQL_DATABASE: shop
        MYSQL_USER: user
        MYSQL_PASSWORD: password
        MYSQL_ROOT_PASSWORD: root

